Refactored code to improve control and error handling
LyubomirT/discord-lle pull request #8
Opened 2023-12-26 18:08 UTC by xZyzz7

Refactored code in `generate_config()` by dividing it into two smaller functions `config_options()` and `config_push()` for improved readability and error handling.

Made some changes to `verify_dir()` and `overwrite_confirmation()` by removing `if not os.path.exists(directory):`  keeping this check in `generate_config()` is better to give us more control over the functions for error handling

2023-12-26 18:15 UTC, LyubomirT requested changes
If possible, could you please only apply error handling? The new code looks a bit overcomplicated and seemingly would be better if left as it is in terms of structure.

2023-12-26 22:13 UTC, xZyzz7 commented
The new code may look a bit overcomplicated because of a lot of refactoring but in reality i didn't change anything really just then main function `generate_config()` was doing a lot so i substracted some of its instruction into two functions. Tell me what part of the code look complicated i'll happily explain.

2023-12-27 07:47 UTC, LyubomirT commented
> The new code may look a bit overcomplicated because of a lot of refactoring but in reality i didn't change anything really just then main function `generate_config()` was doing a lot so i substracted some of its instruction into two functions. Tell me what part of the code look complicated i'll happily explain.

Personally, I don't have any issues understanding the code, but I'm worried about future contributors. However, considering that the config generator won't be actively modified, there should be no big issues with that. Thank you for your contribution! :)

I'll review the changes the second time real quick, and will merge right after that.

2023-12-27 14:02 UTC, LyubomirT approved these changes

2023-12-27 14:02 UTC, merged